### PR TITLE
Added shorthand for production() as p()

### PR DESCRIPTION
**Pull request by Odame**

### CODE REVIEW

**Review by jaxtisapia — APPROVED** [review]

**Review by jaxtisapia — CHANGES_REQUESTED** [review]
please make few changes to logger.test.js

1. since `p()`, `prod()` and `production()` are same functions, let all of these 3 functions be in one `describe()` , instead of separate `describe()` domains. Makes it more organized.

2. Adding `@type {LoggaBat}` to test variables makes it more unreadable. since we wont be generating jsdocs for the tests, let's `eliminate` them

Aside these, PERFECT

**Comment by Odame** [comment]
The` {@type LoggaBat}` makes code completion and intellisense work quite fine. I will take them out anyway

**Comment by Odame** [comment]
I've added the requested changes, you can check and merge it

**Review by jaxtisapia — APPROVED** [review]

**Comment by jaxtisapia** [comment]
@Odame thanks a lot for your contribution. :)

**Pull request merged**
